steps:
    # Setting env vars and the firebase-service-account.json file
    - name: 'bash'
      args:
        - -c
        - |
            echo "$$GOOGLE_CREDENTIALS" > /workspace/firebase-service-account.json
            echo "BOT_TOKEN: '$$BOT_TOKEN'" >> /workspace/env.yaml
            echo "CHAT_ID: '$$CHAT_ID'" >> /workspace/env.yaml
      secretEnv: ['GOOGLE_CREDENTIALS', 'BOT_TOKEN', 'CHAT_ID']
    - name: 'node'
      entrypoint: 'yarn'
      args: ['install']
    - name: 'node'
      entrypoint: 'yarn'
      args: ['build']
    # Installing chromium. This assumes cloud-functions and the node container are the same.
    # Should be more specific in the future.
    - name: 'node:16'
      entrypoint: 'bash'
      args:
        - -c
        - |
            CHROMIUM_PATH=$$(npx --yes @puppeteer/browsers install chromium --path /workspace | cut -d' ' -f2)
            echo "PUPPETEER_EXECUTABLE_PATH: $${CHROMIUM_PATH}" >> /workspace/env.yaml
    # Deploying the function itself:
    # Region is to your liking but make sure your bucket is in the same one
    # trigger-topic must be a predefined topic that your publish messages from a cloud scheduler job
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
        - gcloud
        - functions
        - deploy
        - finance-scraper
        - --region=europe-west1
        - --source=.
        - --trigger-topic=scrape-finance
        - --runtime=nodejs16
        - --entry-point=schedulerHandler
        - --allow-unauthenticated
        - --memory=1024M
        - --env-vars-file=/workspace/env.yaml
availableSecrets:
    secretManager:
    - versionName: projects/$PROJECT_ID/secrets/finance-scraper-bot-token/versions/latest
      env: BOT_TOKEN
    - versionName: projects/$PROJECT_ID/secrets/finance-scraper-chat-id/versions/latest
      env: CHAT_ID
    - versionName: projects/$PROJECT_ID/secrets/finance-scraper-google-credentials/versions/latest
      env: GOOGLE_CREDENTIALS

