service: scraper

provider:
    project: shovi-functions
    region: europe-west1
    name: google
    runtime: nodejs8
    timeout: 540s
    credentials: ./firebase-service-account.json
    package:
        exclude:
            - node_modules/**
functions:
    scrape:
        handler: default
        package:
            include:
                -firebase-service-account.json
        events:
            - http: scrape

plugins:
    - serverless-plugin-typescript
    - serverless-google-cloudfunctions
