service: finance

provider:
    name: aws
    runtime: nodejs8.10
    timeout: 900
#    iamRoleStatements:
#        - Effect: Allow # note that these rights are given in the default policy and are required if we override the iam policies
#          Action:
#              - logs:CreateLogGroup
#              - logs:CreateLogStream
#              - logs:PutLogEvents
#          Resource:
#              - 'Fn::Join':
#                    - ':'
#                    - - 'arn:aws:logs'
#                      - Ref: 'AWS::Region'
#                      - Ref: 'AWS::AccountId'
#                      - 'log-group:/aws/lambda/*:*:*'
#              - Effect: "Allow"
#                Action:
#                    - "ses:SendEmail"
#                Resource:
#                    - "*"
functions:
    scrape:
        handler: src/functions/scrape/index.default
        package:
            include:
                -firebase-service-account.json

plugins:
    - serverless-plugin-typescript
    - serverless-step-functions
